package com.langmy.jFinal.model.base;

import cn.dreampie.web.model.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSecToken<M extends BaseSecToken<M>> extends Model<M> implements IBean {

	public void setUuid(java.lang.String uuid) {
		set("uuid", uuid);
	}

	public java.lang.String getUuid() {
		return get("uuid");
	}

	public void setUsername(java.lang.String username) {
		set("username", username);
	}

	public java.lang.String getUsername() {
		return get("username");
	}

	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}

	public java.util.Date getCreatedAt() {
		return get("created_at");
	}

	public void setExpirationAt(java.util.Date expirationAt) {
		set("expiration_at", expirationAt);
	}

	public java.util.Date getExpirationAt() {
		return get("expiration_at");
	}

	public void setUsedTo(java.lang.Integer usedTo) {
		set("used_to", usedTo);
	}

	public java.lang.Integer getUsedTo() {
		return get("used_to");
	}

}
