package com.langmy.jFinal.model.base;

import cn.dreampie.web.model.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBlogReply<M extends BaseBlogReply<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}

	public java.math.BigInteger getId() {
		return get("id");
	}

	public void setBlogId(java.lang.Integer blogId) {
		set("blog_id", blogId);
	}

	public java.lang.Integer getBlogId() {
		return get("blog_id");
	}

	public void setReplyId(java.lang.Integer replyId) {
		set("reply_id", replyId);
	}

	public java.lang.Integer getReplyId() {
		return get("reply_id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

	public void setBody(java.lang.String body) {
		set("body", body);
	}

	public java.lang.String getBody() {
		return get("body");
	}

	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}

	public java.util.Date getCreatedAt() {
		return get("created_at");
	}

	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}

	public java.util.Date getUpdatedAt() {
		return get("updated_at");
	}

	public void setDeletedAt(java.util.Date deletedAt) {
		set("deleted_at", deletedAt);
	}

	public java.util.Date getDeletedAt() {
		return get("deleted_at");
	}

}
