package com.langmy.jFinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProjectResource<M extends BaseProjectResource<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}

	public java.math.BigInteger getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setContactId(java.lang.Integer contactId) {
		set("contact_id", contactId);
	}

	public java.lang.Integer getContactId() {
		return get("contact_id");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setReadyAt(java.util.Date readyAt) {
		set("ready_at", readyAt);
	}

	public java.util.Date getReadyAt() {
		return get("ready_at");
	}

	public void setActualReadyAt(java.util.Date actualReadyAt) {
		set("actual_ready_at", actualReadyAt);
	}

	public java.util.Date getActualReadyAt() {
		return get("actual_ready_at");
	}

	public void setUseAt(java.util.Date useAt) {
		set("use_at", useAt);
	}

	public java.util.Date getUseAt() {
		return get("use_at");
	}

	public void setActualUseAt(java.util.Date actualUseAt) {
		set("actual_use_at", actualUseAt);
	}

	public java.util.Date getActualUseAt() {
		return get("actual_use_at");
	}

	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}

	public java.util.Date getCreatedAt() {
		return get("created_at");
	}

	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}

	public java.util.Date getUpdatedAt() {
		return get("updated_at");
	}

	public void setDeletedAt(java.util.Date deletedAt) {
		set("deleted_at", deletedAt);
	}

	public java.util.Date getDeletedAt() {
		return get("deleted_at");
	}

}
