package com.langmy.jFinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZcUser<M extends BaseZcUser<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}

	public java.math.BigInteger getId() {
		return get("id");
	}

	public void setUserAcc(java.lang.String userAcc) {
		set("user_acc", userAcc);
	}

	public java.lang.String getUserAcc() {
		return get("user_acc");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setSex(java.lang.Boolean sex) {
		set("sex", sex);
	}

	public java.lang.Boolean getSex() {
		return get("sex");
	}

}
