package com.shoukeplus.jFinal.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRollImages<M extends BaseRollImages<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setDictId(java.lang.Integer dictId) {
		set("dictId", dictId);
	}

	public java.lang.Integer getDictId() {
		return get("dictId");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setIntroduction(java.lang.String introduction) {
		set("introduction", introduction);
	}

	public java.lang.String getIntroduction() {
		return get("introduction");
	}

	public void setImgSrc(java.lang.String imgSrc) {
		set("imgSrc", imgSrc);
	}

	public java.lang.String getImgSrc() {
		return get("imgSrc");
	}

	public void setLinkUrl(java.lang.String linkUrl) {
		set("linkUrl", linkUrl);
	}

	public java.lang.String getLinkUrl() {
		return get("linkUrl");
	}

	public void setTarget(java.lang.String target) {
		set("target", target);
	}

	public java.lang.String getTarget() {
		return get("target");
	}

	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}

	public java.lang.Integer getSort() {
		return get("sort");
	}

	public void setCreatedTime(java.util.Date createdTime) {
		set("createdTime", createdTime);
	}

	public java.util.Date getCreatedTime() {
		return get("createdTime");
	}

	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updatedTime", updatedTime);
	}

	public java.util.Date getUpdatedTime() {
		return get("updatedTime");
	}

}
