package com.shoukeplus.jFinal.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseNewsImages<M extends BaseNewsImages<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setNewsId(java.lang.Integer newsId) {
		set("newsId", newsId);
	}

	public java.lang.Integer getNewsId() {
		return get("newsId");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setImg(java.lang.String img) {
		set("img", img);
	}

	public java.lang.String getImg() {
		return get("img");
	}

	public void setCreatedTime(java.util.Date createdTime) {
		set("createdTime", createdTime);
	}

	public java.util.Date getCreatedTime() {
		return get("createdTime");
	}

}
