package com.shoukeplus.jFinal.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setNickname(java.lang.String nickname) {
		set("nickname", nickname);
	}

	public java.lang.String getNickname() {
		return get("nickname");
	}

	public void setScore(java.lang.Integer score) {
		set("score", score);
	}

	public java.lang.Integer getScore() {
		return get("score");
	}

	public void setToken(java.lang.String token) {
		set("token", token);
	}

	public java.lang.String getToken() {
		return get("token");
	}

	public void setAvatar(java.lang.String avatar) {
		set("avatar", avatar);
	}

	public java.lang.String getAvatar() {
		return get("avatar");
	}

	public void setMission(java.util.Date mission) {
		set("mission", mission);
	}

	public java.util.Date getMission() {
		return get("mission");
	}

	public void setInTime(java.util.Date inTime) {
		set("in_time", inTime);
	}

	public java.util.Date getInTime() {
		return get("in_time");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}

	public java.lang.String getEmail() {
		return get("email");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public void setUrl(java.lang.String url) {
		set("url", url);
	}

	public java.lang.String getUrl() {
		return get("url");
	}

	public void setSignature(java.lang.String signature) {
		set("signature", signature);
	}

	public java.lang.String getSignature() {
		return get("signature");
	}

	public void setQqOpenId(java.lang.String qqOpenId) {
		set("qq_open_id", qqOpenId);
	}

	public java.lang.String getQqOpenId() {
		return get("qq_open_id");
	}

	public void setQqAvatar(java.lang.String qqAvatar) {
		set("qq_avatar", qqAvatar);
	}

	public java.lang.String getQqAvatar() {
		return get("qq_avatar");
	}

	public void setQqNickname(java.lang.String qqNickname) {
		set("qq_nickname", qqNickname);
	}

	public java.lang.String getQqNickname() {
		return get("qq_nickname");
	}

	public void setSinaOpenId(java.lang.String sinaOpenId) {
		set("sina_open_id", sinaOpenId);
	}

	public java.lang.String getSinaOpenId() {
		return get("sina_open_id");
	}

	public void setSinaAvatar(java.lang.String sinaAvatar) {
		set("sina_avatar", sinaAvatar);
	}

	public java.lang.String getSinaAvatar() {
		return get("sina_avatar");
	}

	public void setSinaNickname(java.lang.String sinaNickname) {
		set("sina_nickname", sinaNickname);
	}

	public java.lang.String getSinaNickname() {
		return get("sina_nickname");
	}

}
