package com.shoukeplus.jFinal.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseReply<M extends BaseReply<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setTid(java.lang.String tid) {
		set("tid", tid);
	}

	public java.lang.String getTid() {
		return get("tid");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setInTime(java.util.Date inTime) {
		set("in_time", inTime);
	}

	public java.util.Date getInTime() {
		return get("in_time");
	}

	public void setAuthorId(java.lang.String authorId) {
		set("author_id", authorId);
	}

	public java.lang.String getAuthorId() {
		return get("author_id");
	}

	public void setBest(java.lang.Integer best) {
		set("best", best);
	}

	public java.lang.Integer getBest() {
		return get("best");
	}

	public void setIsdelete(java.lang.Integer isdelete) {
		set("isdelete", isdelete);
	}

	public java.lang.Integer getIsdelete() {
		return get("isdelete");
	}

}
