package com.langmy.jFinal.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBlog<M extends BaseBlog<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}

	public java.math.BigInteger getId() {
		return get("id");
	}

	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}

	public java.lang.Long getUserId() {
		return get("user_id");
	}

	public void setTopped(java.lang.Integer topped) {
		set("topped", topped);
	}

	public java.lang.Integer getTopped() {
		return get("topped");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public void setTags(java.lang.String tags) {
		set("tags", tags);
	}

	public java.lang.String getTags() {
		return get("tags");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setBody(java.lang.String body) {
		set("body", body);
	}

	public java.lang.String getBody() {
		return get("body");
	}

	public void setCompleted(java.lang.Integer completed) {
		set("completed", completed);
	}

	public java.lang.Integer getCompleted() {
		return get("completed");
	}

	public void setHitCount(java.lang.Integer hitCount) {
		set("hit_count", hitCount);
	}

	public java.lang.Integer getHitCount() {
		return get("hit_count");
	}

	public void setFeedCount(java.lang.Integer feedCount) {
		set("feed_count", feedCount);
	}

	public java.lang.Integer getFeedCount() {
		return get("feed_count");
	}

	public void setReplayCount(java.lang.Integer replayCount) {
		set("replay_count", replayCount);
	}

	public java.lang.Integer getReplayCount() {
		return get("replay_count");
	}

	public void setNoReply(java.lang.Integer noReply) {
		set("no_reply", noReply);
	}

	public java.lang.Integer getNoReply() {
		return get("no_reply");
	}

	public void setCollectCount(java.lang.Integer collectCount) {
		set("collect_count", collectCount);
	}

	public java.lang.Integer getCollectCount() {
		return get("collect_count");
	}

	public void setOpened(java.lang.Integer opened) {
		set("opened", opened);
	}

	public java.lang.Integer getOpened() {
		return get("opened");
	}

	public void setSupportCount(java.lang.Integer supportCount) {
		set("support_count", supportCount);
	}

	public java.lang.Integer getSupportCount() {
		return get("support_count");
	}

	public void setOpposeCount(java.lang.Integer opposeCount) {
		set("oppose_count", opposeCount);
	}

	public java.lang.Integer getOpposeCount() {
		return get("oppose_count");
	}

	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}

	public java.util.Date getCreatedAt() {
		return get("created_at");
	}

	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}

	public java.util.Date getUpdatedAt() {
		return get("updated_at");
	}

	public void setDeletedAt(java.util.Date deletedAt) {
		set("deleted_at", deletedAt);
	}

	public java.util.Date getDeletedAt() {
		return get("deleted_at");
	}

}
