package com.langmy.jFinal.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTaskDepend<M extends BaseTaskDepend<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}

	public java.math.BigInteger getId() {
		return get("id");
	}

	public void setMainId(java.lang.Integer mainId) {
		set("main_id", mainId);
	}

	public java.lang.Integer getMainId() {
		return get("main_id");
	}

	public void setSubId(java.lang.Integer subId) {
		set("sub_id", subId);
	}

	public java.lang.Integer getSubId() {
		return get("sub_id");
	}

}
