package com.langmy.jFinal.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTopic<M extends BaseTopic<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setSId(java.lang.Integer sId) {
		set("s_id", sId);
	}

	public java.lang.Integer getSId() {
		return get("s_id");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setInTime(java.util.Date inTime) {
		set("in_time", inTime);
	}

	public java.util.Date getInTime() {
		return get("in_time");
	}

	public void setModifyTime(java.util.Date modifyTime) {
		set("modify_time", modifyTime);
	}

	public java.util.Date getModifyTime() {
		return get("modify_time");
	}

	public void setLastReplyTime(java.util.Date lastReplyTime) {
		set("last_reply_time", lastReplyTime);
	}

	public java.util.Date getLastReplyTime() {
		return get("last_reply_time");
	}

	public void setLastReplyAuthorId(java.lang.String lastReplyAuthorId) {
		set("last_reply_author_id", lastReplyAuthorId);
	}

	public java.lang.String getLastReplyAuthorId() {
		return get("last_reply_author_id");
	}

	public void setView(java.lang.Integer view) {
		set("view", view);
	}

	public java.lang.Integer getView() {
		return get("view");
	}

	public void setAuthorId(java.lang.String authorId) {
		set("author_id", authorId);
	}

	public java.lang.String getAuthorId() {
		return get("author_id");
	}

	public void setTop(java.lang.Integer top) {
		set("top", top);
	}

	public java.lang.Integer getTop() {
		return get("top");
	}

	public void setGood(java.lang.Integer good) {
		set("good", good);
	}

	public java.lang.Integer getGood() {
		return get("good");
	}

	public void setShowStatus(java.lang.Integer showStatus) {
		set("show_status", showStatus);
	}

	public java.lang.Integer getShowStatus() {
		return get("show_status");
	}

	public void setReplyCount(java.lang.Integer replyCount) {
		set("reply_count", replyCount);
	}

	public java.lang.Integer getReplyCount() {
		return get("reply_count");
	}

	public void setIsdelete(java.lang.Integer isdelete) {
		set("isdelete", isdelete);
	}

	public java.lang.Integer getIsdelete() {
		return get("isdelete");
	}

}
