package com.langmy.jFinal.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSection<M extends BaseSection<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setTab(java.lang.String tab) {
		set("tab", tab);
	}

	public java.lang.String getTab() {
		return get("tab");
	}

	public void setShowStatus(java.lang.Integer showStatus) {
		set("show_status", showStatus);
	}

	public java.lang.Integer getShowStatus() {
		return get("show_status");
	}

	public void setDisplayIndex(java.lang.Integer displayIndex) {
		set("display_index", displayIndex);
	}

	public java.lang.Integer getDisplayIndex() {
		return get("display_index");
	}

	public void setDefaultShow(java.lang.Integer defaultShow) {
		set("default_show", defaultShow);
	}

	public java.lang.Integer getDefaultShow() {
		return get("default_show");
	}

}
