package com.langmy.jFinal.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMsgContact<M extends BaseMsgContact<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setAuthorId(java.lang.String authorId) {
		set("author_id", authorId);
	}

	public java.lang.String getAuthorId() {
		return get("author_id");
	}

	public void setToAuthorId(java.lang.String toAuthorId) {
		set("to_author_id", toAuthorId);
	}

	public java.lang.String getToAuthorId() {
		return get("to_author_id");
	}

	public void setMsgCount(java.lang.Integer msgCount) {
		set("msg_count", msgCount);
	}

	public java.lang.Integer getMsgCount() {
		return get("msg_count");
	}

	public void setLastMsgContent(java.lang.String lastMsgContent) {
		set("last_msg_content", lastMsgContent);
	}

	public java.lang.String getLastMsgContent() {
		return get("last_msg_content");
	}

	public void setInTime(java.util.Date inTime) {
		set("in_time", inTime);
	}

	public java.util.Date getInTime() {
		return get("in_time");
	}

	public void setLastMsgTime(java.util.Date lastMsgTime) {
		set("last_msg_time", lastMsgTime);
	}

	public java.util.Date getLastMsgTime() {
		return get("last_msg_time");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}

	public java.lang.Integer getIsDelete() {
		return get("is_delete");
	}

}
