package com.langmy.jFinal.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("blog", "id", Blog.class);
		arp.addMapping("blog_reply", "id", BlogReply.class);
		arp.addMapping("com_area", "id", ComArea.class);
		arp.addMapping("com_state", "id", ComState.class);
		arp.addMapping("department", "id", Department.class);
		arp.addMapping("follower", "id", Follower.class);
		arp.addMapping("project", "id", Project.class);
		arp.addMapping("project_group", "id", ProjectGroup.class);
		arp.addMapping("project_resource", "id", ProjectResource.class);
		arp.addMapping("sec_menu", "id", Menu.class);
		arp.addMapping("sec_permission", "id", Permission.class);
		arp.addMapping("sec_role", "id", Role.class);
		arp.addMapping("sec_role_menu", "id", RoleMenu.class);
		arp.addMapping("sec_role_permission", "id", RolePermission.class);
		arp.addMapping("sec_token", "uuid", Token.class);
		arp.addMapping("sec_user", "id", User.class);
		arp.addMapping("sec_user_info", "id", UserInfo.class);
		arp.addMapping("sec_user_menu", "id", UserMenu.class);
		arp.addMapping("sec_user_role", "id", UserRole.class);
		arp.addMapping("side_task", "id", SideTask.class);
		arp.addMapping("side_task_assist", "id", SideTaskAssist.class);
		arp.addMapping("task", "id", Task.class);
		arp.addMapping("task_depend", "id", TaskDepend.class);
		arp.addMapping("task_group", "id", TaskGroup.class);
		arp.addMapping("zc_user", "id", ZcUser.class);
	}
}

