package com.langmy.jFinal.model;

import com.langmy.jFinal.model.base.BaseComArea;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ComArea extends BaseComArea<ComArea> {
	public static final ComArea dao = new ComArea();
}
