package com.langmy.jFinal.model;

import com.langmy.jFinal.model.base.BaseComState;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ComState extends BaseComState<ComState> {
	public static final ComState dao = new ComState();
}
