package com.langmy.jFinal.model;

import com.langmy.jFinal.model.base.BaseFollower;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Follower extends BaseFollower<Follower> {
	public static final Follower dao = new Follower();
}
