package com.langmy.jFinal.model;

import cn.dreampie.sqlinxml.SqlKit;
import com.langmy.jFinal.model.base.BaseMenu;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Menu extends BaseMenu<Menu> {
	public static final Menu dao = new Menu();

	public List<Menu> findByRole(String where, Object... paras) {
		return find(getSelectSql() + SqlKit.sql("menu.findRoleByExceptSelect") + blank + getWhere(where), paras);
	}
}
