package com.langmy.jFinal.model;

import com.jfinal.plugin.activerecord.Db;
import com.langmy.jFinal.model.base.BaseRolePermission;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RolePermission extends BaseRolePermission<RolePermission> {
	public static final RolePermission dao = new RolePermission();
	public List<String> findPermissionIds(String where, Object... paras) {
		return Db.query("SELECT DISTINCT `rolePermission`.permission_id " + getFromSql() + getWhere(where), paras);
	}
}
