package com.langmy.jFinal.model;

import cn.dreampie.ValidateKit;
import cn.dreampie.sqlinxml.SqlKit;
import com.jfinal.plugin.activerecord.Db;
import com.langmy.jFinal.config.AppConstants;
import com.langmy.jFinal.model.base.BaseRole;

import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Role extends BaseRole<Role> {
	public static final Role dao = new Role();

	public void initPermissiones() {
		this.put("permissiones", Permission.dao.findByRole("", this.getInt("id")));
	}

	public List<Permission> getPermissiones() {
		return this.get("permissiones");
	}

	public Role addPermission(Permission permission) {
		if (ValidateKit.isNullOrEmpty(permission)) {
			throw new NullPointerException("操作权限不存在");
		}
		RolePermission rolePermission = new RolePermission();
		rolePermission.set("role_id", this.get("id"));
		rolePermission.set("permission_id", permission.get("id"));
		rolePermission.save();

		return this;
	}

	public List<Role> findUserBy(String where, Object... paras) {
		return find(getSelectSql() + SqlKit.sql("role.findUserByExceptSelect") + blank + getWhere(where), paras);
	}

	public List<Role> findChildrenById(String where, Object... paras) {
		return find(getSelectSql() + SqlKit.sql("role.findChildrenByExceptSelect") + blank + getWhere(where), paras);
	}

	public List<Long> findChildrenIdsById(String where, Object... paras) {
		return Db.query("SELECT `role`.id " + SqlKit.sql("role.findChildrenByExceptSelect") + blank + getWhere(where), paras);
	}

	public List<Role> findAll() {
		return super.find("select * from jfbbs_role");
	}

	public Set<String> findRoles(String username) {
		List<Role> roles = super.findByCache(AppConstants.SHIROCACHE, AppConstants.ROLECACHEKEY + username,
				"select r.* from sec_user u, sec_role r, sec_user_role ur where u.id = ur.user_id and r.id = ur.role_id and u.username = ?", username);
		Set<String> set = new HashSet<String>();
		for (Role r : roles) {
			set.add(r.getStr("name"));
		}
		return set;
	}

	public void correlationPermission(Integer roleId, Integer[] permissionIds) {
		//先删除已经存在的关联
		Db.update("delete from sec_role_permission where rid = ?", roleId);
		//建立新的关联关系
		for (Integer pid : permissionIds) {
			RolePermission rolePermission = new RolePermission();
			rolePermission.set("role_id", roleId)
					.set("permission_id", pid)
					.save();
		}
	}
}
