package com.langmy.jFinal.model;

import com.jfinal.plugin.activerecord.Db;
import com.langmy.jFinal.model.base.BaseRoleMenu;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoleMenu extends BaseRoleMenu<RoleMenu> {
	public static final RoleMenu dao = new RoleMenu();

	public List<String> findMenuIds(String where, Object... paras) {
		return Db.query("SELECT DISTINCT `roleMenu`.menu_id " + getFromSql() + getWhere(where), paras);
	}
}
