package com.langmy.jFinal.model;

import com.langmy.jFinal.model.base.BaseRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Role extends BaseRole<Role> {
	public static final Role dao = new Role();
}
