package com.langmy.jFinal.model;

import com.langmy.jFinal.common.utils.StrUtil;
import com.langmy.jFinal.config.AppConstants;
import com.langmy.jFinal.model.base.BaseSysConfig;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysConfig extends BaseSysConfig<SysConfig> {
	public static final SysConfig dao = new SysConfig();

	/**
	 * 根据key查询value,并放入缓存里
	 *
	 * @param key
	 * @return
	 */
	public String findByKey(String key) {
		if (!StrUtil.isBlank(key)) {
			Map<String, Object> map = findAll2Map();
			return map.get(key).toString();
		}
		return null;
	}

	public Map<String, Object> findAll2Map() {
		List<SysConfig> list = super.findByCache(
				AppConstants.SYSCONFIGCACHE,
				AppConstants.SYSCONFIGCACHEKEY,
				"select * from com_sys_config"
		);
		Map<String, Object> map = new HashMap<String, Object>();
		for (SysConfig sc : list) {
			map.put(sc.getStr("key"), sc.getStr("value"));
		}
		return map;
	}

	public void update(String key, String value) {
		if (!StrUtil.isBlank(value)) {
			SysConfig sysConfig = findFirst("select * from com_sys_config where `key` = ?", key);
			if (sysConfig != null) {
				sysConfig.set("value", value);
				sysConfig.update();
			}
		}
	}
}
