package com.langmy.jFinal.model;

import com.langmy.jFinal.model.base.BaseTaskGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TaskGroup extends BaseTaskGroup<TaskGroup> {
	public static final TaskGroup dao = new TaskGroup();
}
