package com.langmy.jFinal.model;

import com.langmy.jFinal.model.base.BaseToken;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Token extends BaseToken<Token> {
	public static final Token dao = new Token();
}
