package com.langmy.jFinal.model;

import com.langmy.jFinal.model.base.BaseUserMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserMenu extends BaseUserMenu<UserMenu> {
	public static final UserMenu dao = new UserMenu();
}
