package com.langmy.jFinal.model;

import cn.dreampie.sqlinxml.SqlKit;
import com.jfinal.plugin.activerecord.Db;
import com.langmy.jFinal.model.base.BaseUserRole;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserRole extends BaseUserRole<UserRole> {
	public static final UserRole dao = new UserRole();

	public Role getRole() {
		return Role.dao.findById(this.get("role_id"));
	}


	public List<String> findUserIds(String where, Object... paras) {
		return Db.query("SELECT DISTINCT `userRole`.user_id " + SqlKit.sql("userRole.findByExceptSelect") + " " + getWhere(where), paras);
	}
}
