package com.langmy.jFinal.model;

import com.jfinal.plugin.activerecord.Db;
import com.langmy.jFinal.model.base.BaseUserMenu;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserMenu extends BaseUserMenu<UserMenu> {
	public static final UserMenu dao = new UserMenu();
	public List<String> findMenuIds(String where, Object... paras) {
		return Db.query("SELECT DISTINCT `userMenu`.menu_id " + getFromSql() + getWhere(where), paras);
	}
}
