package com.langmy.jFinal.model;

import com.langmy.jFinal.model.base.BaseZcUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZcUser extends BaseZcUser<ZcUser> {
	public static final ZcUser dao = new ZcUser();
}
