package com.langmy.jFinal.common.model;

import com.langmy.jFinal.common.model.base.BaseAdminLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminLog extends BaseAdminLog<AdminLog> {
	public static final AdminLog dao = new AdminLog();
}
