package com.langmy.jFinal.common.model;

import com.langmy.jFinal.common.model.base.BaseArea;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Area extends BaseArea<Area> {
	public static final Area dao = new Area();
}
