package com.langmy.jFinal.common.model;

import com.langmy.jFinal.common.model.base.BaseBlogReply;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BlogReply extends BaseBlogReply<BlogReply> {
	public static final BlogReply dao = new BlogReply();
}
