package com.langmy.jFinal.common.model;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;
import com.langmy.jFinal.common.model.base.BaseCollect;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Collect extends BaseCollect<Collect> {
	public static final Collect dao = new Collect();
	public Page<Collect> findByAuthorId(int pageNumber, int pageSize, String authorId) {
		return super.paginate(pageNumber, pageSize, "select * ", "from sk_collect where author_id = ?", authorId);
	}

	public List<Collect> findByTid(String tid) {
		return super.find("select * from sk_collect where tid = ?", tid);
	}

	public Collect findByTidAndAuthorId(String tid, String authorId) {
		return super.findFirst("select * from sk_collect where tid = ? and author_id = ?", tid, authorId);
	}

	public boolean deleteByTidAndAuthorId(String tid, String authorId) {
		Collect collect = findByTidAndAuthorId(tid, authorId);
		return super.deleteById(collect.get("id"));
	}

	public Page<Collect> findByAuthorIdWithTopic(int pageNumber, int pageSize, String authorId) {
		return super.paginate(pageNumber, pageSize, " select t.*, s.name as sectionName, s.tab, u.avatar, " +
						" (select u.avatar from sk_user u where u.id = t.last_reply_author_id) as last_reply_author_avatar ",
				" from sk_collect c left join sk_topic t on c.tid = t.id " +
						" left join sk_section s on s.id = t.s_id " +
						" left join sk_user u on u.id = t.author_id " +
						" where t.isdelete = 0 and c.author_id = ?", authorId);
	}

	public List<Collect> findByAuthorIdWithTopic(String authorId) {
		return super.find("select t.*, s.name as sectionName, s.tab, u.avatar, u.nickname" +
				" from sk_collect c left join sk_topic t on c.tid = t.id " +
				" left join sk_section s on s.id = t.s_id " +
				" left join sk_user u on u.id = t.author_id " +
				" where t.isdelete = 0 and c.author_id = ?", authorId);
	}

	public int deleteByTid(String tid) {
		return Db.update("delete from sk_collect where tid = ?", tid);
	}
}
