package com.langmy.jFinal.common.model;

import com.langmy.jFinal.common.model.base.BaseDonate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Donate extends BaseDonate<Donate> {
	public static final Donate dao = new Donate();
}
