package com.langmy.jFinal.common.model;

import com.langmy.jFinal.common.model.base.BaseLabel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Label extends BaseLabel<Label> {
	public static final Label dao = new Label();
}
