package com.langmy.jFinal.common.model;

import com.langmy.jFinal.common.model.base.BaseLabelTopicId;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LabelTopicId extends BaseLabelTopicId<LabelTopicId> {
	public static final LabelTopicId dao = new LabelTopicId();
}
