package com.langmy.jFinal.common.model;

import com.langmy.jFinal.common.model.base.BaseMsgContact;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MsgContact extends BaseMsgContact<MsgContact> {
	public static final MsgContact dao = new MsgContact();
}
