package com.langmy.jFinal.common.model;

import com.langmy.jFinal.common.model.base.BaseNotification;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Notification extends BaseNotification<Notification> {
	public static final Notification dao = new Notification();
}
