package com.langmy.jFinal.common.model;

import com.langmy.jFinal.common.model.base.BaseProjectGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProjectGroup extends BaseProjectGroup<ProjectGroup> {
	public static final ProjectGroup dao = new ProjectGroup();
}
