package com.langmy.jFinal.common.model;

import com.langmy.jFinal.common.model.base.BaseProject;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Project extends BaseProject<Project> {
	public static final Project dao = new Project();
}
