package com.langmy.jFinal.common.model;

import com.langmy.jFinal.common.model.base.BaseProjectResource;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProjectResource extends BaseProjectResource<ProjectResource> {
	public static final ProjectResource dao = new ProjectResource();
}
