package com.langmy.jFinal.common.model;

import com.jfinal.plugin.activerecord.Db;
import com.langmy.jFinal.common.model.base.BaseRolePermission;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RolePermission extends BaseRolePermission<RolePermission> {
	public static final RolePermission dao = new RolePermission();
	public List<RolePermission> findByRoleId(Integer roleId) {
		return super.find("select * from sk_role_permission where rid = ?", roleId);
	}

	public void deleteByPermissionId(Integer permissionId) {
		Db.update("delete from sk_role_permission where pid = ?", permissionId);
	}

	public void deleteByRoleId(Integer roleId) {
		Db.update("delete from sk_role_permission where rid = ?", roleId);
	}
}
