package com.langmy.jFinal.common.model;

import com.jfinal.plugin.activerecord.Db;
import com.langmy.jFinal.common.AppConstants;
import com.langmy.jFinal.common.model.base.BaseRole;

import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Role extends BaseRole<Role> {
	public static final Role dao = new Role();

	public List<Role> findAll() {
		return super.find("select * from sec_role");
	}

	public Set<String> findRoles(String username) {
		List<Role> roles = super.findByCache(AppConstants.SHIROCACHE, AppConstants.ROLECACHEKEY + username,
				"select r.* from sec_user u, sec_role r, sec_user_role ur where u.id = ur.user_id and r.id = ur.role_id and u.username = ?", username);
		Set<String> set = new HashSet<String>();
		for (Role r : roles) {
			set.add(r.getStr("name"));
		}
		return set;
	}

	public void correlationPermission(Integer roleId, Integer[] permissionIds) {
		//先删除已经存在的关联
		Db.update("delete from sec_role_permission where rid = ?", roleId);
		//建立新的关联关系
		for (Integer pid : permissionIds) {
			RolePermission rolePermission = new RolePermission();
			rolePermission.set("role_id", roleId)
					.set("permission_id", pid)
					.save();
		}
	}
}
