package com.langmy.jFinal.common.model;

import com.langmy.jFinal.common.model.base.BaseSideTask;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SideTask extends BaseSideTask<SideTask> {
	public static final SideTask dao = new SideTask();
}
