package com.langmy.jFinal.common.model;

import com.langmy.jFinal.common.model.base.BaseSideTaskAssist;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SideTaskAssist extends BaseSideTaskAssist<SideTaskAssist> {
	public static final SideTaskAssist dao = new SideTaskAssist();
}
