package com.langmy.jFinal.common.model;

import com.langmy.jFinal.common.model.base.BaseState;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class State extends BaseState<State> {
	public static final State dao = new State();
}
