package com.langmy.jFinal.common.model;

import com.langmy.jFinal.common.model.base.BaseTask;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Task extends BaseTask<Task> {
	public static final Task dao = new Task();
}
