package com.langmy.jFinal.common.model;

import com.langmy.jFinal.common.model.base.BaseTaskDepend;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TaskDepend extends BaseTaskDepend<TaskDepend> {
	public static final TaskDepend dao = new TaskDepend();
}
