package com.langmy.jFinal.common.model;

import com.jfinal.plugin.activerecord.Db;
import com.langmy.jFinal.common.model.base.BaseUserRole;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserRole extends BaseUserRole<UserRole> {
	public static final UserRole dao = new UserRole();
	public List<UserRole> findByUserId(Integer userId) {
		return super.find("select * from sk_user_role where uid = ?", userId);
	}

	public void deleteByUserId(Integer userId) {
		Db.update("delete from sk_user_role where uid = ?", userId);
	}

	public void deleteByRoleId(Integer roleId) {
		Db.update("delete from sk_user_role where rid = ?", roleId);
	}
}
