package com.shoukeplus.jFinal.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("sk_admin_log", "id", AdminLog.class);
		arp.addMapping("sk_admin_user", "id", AdminUser.class);
		arp.addMapping("sk_area", "areaId", Area.class);
		arp.addMapping("sk_collect", "id", Collect.class);
		arp.addMapping("sk_dict", "id", Dict.class);
		arp.addMapping("sk_donate", "id", Donate.class);
		arp.addMapping("sk_label", "id", Label.class);
		arp.addMapping("sk_label_topic_id", "id", LabelTopicId.class);
		arp.addMapping("sk_link", "id", Link.class);
		arp.addMapping("sk_message", "id", Message.class);
		arp.addMapping("sk_mission", "id", Mission.class);
		arp.addMapping("sk_msg_contact", "id", MsgContact.class);
		arp.addMapping("sk_notification", "id", Notification.class);
		arp.addMapping("sk_permission", "id", Permission.class);
		arp.addMapping("sk_reply", "id", Reply.class);
		arp.addMapping("sk_role", "id", Role.class);
		arp.addMapping("sk_role_permission", "id", RolePermission.class);
		arp.addMapping("sk_section", "id", Section.class);
		arp.addMapping("sk_sys_config", "id", SysConfig.class);
		arp.addMapping("sk_topic", "id", Topic.class);
		arp.addMapping("sk_user", "id", User.class);
		arp.addMapping("sk_user_role", "id", UserRole.class);
		arp.addMapping("sk_valicode", "id", Valicode.class);
	}
}

