package com.shoukeplus.jFinal.common.model;

import com.google.common.base.Joiner;
import com.jfinal.plugin.activerecord.Db;
import com.shoukeplus.jFinal.common.model.base.BaseContentFiles;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ContentFiles extends BaseContentFiles<ContentFiles> {
	public static final ContentFiles dao = new ContentFiles();

	public List<ContentFiles> findByContentId(String contentId) {
		return super.find("select * from sk_content_files where contentId=? order by id", contentId);
	}

	public List<ContentFiles> findIdsByContentId(String contentId) {
		return super.find("select id from sk_content_files where contentId=? order by id", contentId);
	}

	public void deleteByIds(List<String> ids) {
		String idsStr = Joiner.on(",").join(ids);
		Db.update("delete from sk_content_files where id in (" + idsStr + ") ");
	}

}
