package com.shoukeplus.jFinal.common.model;

import com.jfinal.plugin.activerecord.Page;
import com.shoukeplus.jFinal.common.model.base.BaseContent;
import com.shoukeplus.jFinal.common.utils.StrUtil;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Content extends BaseContent<Content> {
	public static final Content dao = new Content();
	public Page<Content> page(int pageNumber, int pageSize, String value, String dictId) {
		StringBuffer condition = new StringBuffer();
		if (!StrUtil.isBlank(value)) condition.append(" and c.title like \"%" + value + "%\" ");
		if (!StrUtil.isBlank(dictId)) condition.append(" and c.dictId = " + dictId);

		String select="select c.*, d.value as categoryName";
		String sqlExceptSelect="from sk_content c left join sk_dict d on c.dictId = d.id left join sk_dict d2 on d.type=d2.key where c.isDeleted = 0 and d2.type='contentCategory' "+condition+" order by d2.sort, d.sort,c.releaseTime desc, c.id desc";

		return super.paginate(pageNumber, pageSize,
				select, sqlExceptSelect);
	}
}
