package com.shoukeplus.jFinal.common.model;

import com.shoukeplus.jFinal.common.model.base.BaseContentFiles;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ContentFiles extends BaseContentFiles<ContentFiles> {
	public static final ContentFiles dao = new ContentFiles();
}
