package com.shoukeplus.jFinal.common.model;

import com.jfinal.plugin.activerecord.Db;
import com.shoukeplus.jFinal.common.model.base.BaseLabelTopicId;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LabelTopicId extends BaseLabelTopicId<LabelTopicId> {
	public static final LabelTopicId dao = new LabelTopicId();
	public int deleteByLid(int lid) {
		return Db.update("delete from sk_label_topic_id where lid = ?", lid);
	}

	public void deleteByTid(String tid) {
		List<LabelTopicId> labelTopicIds = super.find("select * from sk_label_topic_id where tid = ?", tid);
		if (labelTopicIds.size() > 0) {
			for (LabelTopicId lti : labelTopicIds) {
				Db.update("update sk_label set topic_count = (topic_count - 1) where id = ?", lti.get("lid"));
				Db.update("delete from sk_label_topic_id where lid = ? and tid = ?", lti.get("lid"), lti.get("tid"));
			}
		}
	}

	public void save(Integer lid, String tid) {
		LabelTopicId labelTopicId = super.findFirst("select * from sk_label_topic_id where lid = ? and tid = ?", lid, tid);
		if (labelTopicId == null) {
			labelTopicId = new LabelTopicId();
			labelTopicId.set("lid", lid)
					.set("tid", tid).save();
			//更新标签topic_count
			Label label = Label.dao.findById(lid);
			label.set("topic_count", label.getInt("topic_count") + 1).update();
		}
	}

	public List<LabelTopicId> findByTid(String tid) {
		return super.find("select * from sk_label_topic_id where tid = ?", tid);
	}
}
