package com.shoukeplus.jFinal.common.model;

import com.shoukeplus.jFinal.common.model.base.BaseMessage;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Message extends BaseMessage<Message> {
	public static final Message dao = new Message();
	/**
	 * 根据会话id查询会话消息内容
	 *
	 * @param contactId
	 * @return
	 */
	public List<Message> findByContactId(Integer contactId) {
		return super.find("select m.*, u.avatar, u.nickname from sk_message m " +
				"left join sk_user u on m.author_id = u.id " +
				"left join sk_msg_contact mc on m.contact_id = mc.id " +
				"where contact_id = ? and mc.is_delete = 0 order by in_time desc", contactId);
	}

}
