package com.shoukeplus.jFinal.common.model;

import com.shoukeplus.jFinal.common.model.base.BaseNewsImages;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class NewsImages extends BaseNewsImages<NewsImages> {
	public static final NewsImages dao = new NewsImages();
}
