package com.shoukeplus.jFinal.common.model;

import com.google.common.base.Joiner;
import com.jfinal.plugin.activerecord.Db;
import com.shoukeplus.jFinal.common.model.base.BaseNewsImages;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class NewsImages extends BaseNewsImages<NewsImages> {
	public static final NewsImages dao = new NewsImages();
	public List<NewsImages> findByNewsId(String newsId) {
		return super.find("select * from sk_news_images where newsId=? order by id",newsId);
	}
	public List<NewsImages> findIdsByNewsId(String newsId) {
		return super.find("select id from sk_news_images where newsId=? order by id",newsId);
	}
	public void deleteByIds(List<String> ids){
		String idsStr= Joiner.on(",").join(ids);
		Db.update("delete from sk_news_images where id in ("+idsStr+") ");
	}
}
