package com.shoukeplus.jFinal.common.model;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;
import com.shoukeplus.jFinal.common.AppConstants;
import com.shoukeplus.jFinal.common.model.base.BaseRole;

import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Role extends BaseRole<Role> {
	public static final Role dao = new Role();
	public Page<Role> page(Integer pageNumber, Integer pageSize) {
		return super.paginate(pageNumber, pageSize, "select * ", "from sk_role");
	}

	public List<Role> findAll() {
		return super.find("select * from sk_role");
	}

	public Set<String> findRoles(String username) {
		List<Role> roles = super.findByCache(AppConstants.SHIROCACHE, AppConstants.ROLECACHEKEY + username,
				"select r.* from sk_admin_user u, sk_role r, sk_user_role ur where u.id = ur.uid and r.id = ur.rid and u.username = ?", username);
		Set<String> set = new HashSet<String>();
		for (Role r : roles) {
			set.add(r.getStr("name"));
		}
		return set;
	}

	public void correlationPermission(Integer roleId, Integer[] permissionIds) {
		//先删除已经存在的关联
		Db.update("delete from sk_role_permission where rid = ?", roleId);
		//建立新的关联关系
		for (Integer pid : permissionIds) {
			RolePermission rolePermission = new RolePermission();
			rolePermission.set("rid", roleId)
					.set("pid", pid)
					.save();
		}
	}
}
