package com.shoukeplus.jFinal.common.model;

import com.jfinal.plugin.activerecord.Page;
import com.shoukeplus.jFinal.common.model.base.BaseRollImages;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RollImages extends BaseRollImages<RollImages> {
    public static final RollImages dao = new RollImages();

    public List<RollImages> findAll() {
        return super.find("select * from sk_roll_images order by createdTime desc");
    }

    public Page<RollImages> page(int pageNumber, int pageSize, Integer dictId) {
        StringBuffer condition = new StringBuffer();
        if (dictId != -1) condition.append(" and n.dictId = " + dictId);
        return super.paginate(pageNumber, pageSize,
                "select n.* ,d.value as dictName,d2.value as targetValue",
                "from sk_roll_images n left join sk_dict d on n.dictId = d.id left join sk_dict d2 on n.target = d2.key " +
                        "where 1=1 " + condition + "  order by createdTime desc");
    }

}
