package com.shoukeplus.jFinal.common.model;

import com.shoukeplus.jFinal.common.AppConstants;
import com.shoukeplus.jFinal.common.model.base.BaseSection;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Section extends BaseSection<Section> {
	public static final Section dao = new Section();
	public List<Section> findAll() {
		return super.findByCache(AppConstants.SECTIONCACHE, AppConstants.SECTIONLISTKEY, "select * from sk_section order by display_index");
	}

	public List<Section> findShow() {
		return super.findByCache(AppConstants.SECTIONCACHE, AppConstants.SECTIONSHOWLISTKEY, "select * from sk_section where show_status = 1 order by display_index");
	}

	public Section findByTab(String tab) {
		return super.findFirstByCache(AppConstants.SECTIONCACHE, AppConstants.SECTIONBYTABKEY + "-" + tab, "select * from sk_section where tab = ?", tab);
	}

	public Section findDefault() {
		List<Section> sections = super.findByCache(AppConstants.SECTIONCACHE, AppConstants.DEFAULTSECTIONKEY, "select * from sk_section where default_show = 1");
		if (sections.size() > 0) return sections.get(0);
		return null;
	}
}
