package com.shoukeplus.jFinal.common.model;

import com.shoukeplus.jFinal.common.model.base.BaseValicode;
import com.shoukeplus.jFinal.common.utils.DateUtil;

import java.util.Date;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Valicode extends BaseValicode<Valicode> {
	public static final Valicode dao = new Valicode();
	//查询未过期的验证码
	public Valicode findByCodeAndEmail(String code, String email, String type) {
		String nowTime = DateUtil.formatDateTime(new Date());
		return super.findFirst("select * from sk_valicode v where v.status = 0 and v.code = ? and v.target = ? and v.expire_time > ? and v.type = ?", code, email, nowTime, type);
	}
}
